name = "gallery798"
main = "worker/src/index.js"
compatibility_date = "2023-10-25"

[vars]
# Environment variables if needed

[[kv_namespaces]]
binding = "CIVITAI_IMAGES"
id = "c53f36c83672473595723e1d532737c1"
preview_id = "YOUR_PREVIEW_KV_NAMESPACE_ID"

[triggers]
crons = ["0 * * * *"] # Run every hour

[site]
bucket = "./public"
